=== nraa/edelivery-message-format/root/contents/toc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="toc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="body" type="BodyType"></xs:element>
				<xs:element name="attachment-list" type="AttachmentListType" minOccurs="0" maxOccurs="1"></xs:element>
				<xs:element name="link-list" type="LinkListType" minOccurs="0" maxOccurs="1"></xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="attachmentFileRefUniq">
			<xs:selector xpath="./attachment"></xs:selector>
			<xs:field xpath="@fileref"></xs:field>
		</xs:unique>
		<xs:unique name="linkUniq">
			<xs:selector xpath="link"></xs:selector>
			<xs:field xpath="@src"></xs:field>
		</xs:unique>
	</xs:element>
	<xs:complexType name="BodyType">
		<xs:sequence>
			<xs:element name="original-name" type="xs:string"></xs:element>
			<!-- digest-algo = SHA-256 | SHA-512 | SHA-1 etc. -->
			<xs:element name="digest-algo" type="xs:string"></xs:element>
			<xs:element name="digest-value" type="DigestValueType"></xs:element>
			<xs:element name="encrypted" type="EncryptedType" minOccurs="0" maxOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="fileref" type="BodyFileRefType" use="required"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="AttachmentListType">
		<xs:sequence>
			<xs:element name="attachment" type="AttachmentType" minOccurs="1" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LinkListType">
		<xs:sequence>
			<xs:element name="link" type="LinkType" minOccurs="1" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AttachmentType">
		<xs:sequence>
			<xs:element name="original-name" type="xs:string"></xs:element>
			<!-- digest-algo = SHA-256 | SHA-512 | SHA-1 etc. -->
			<xs:element name="digest-algo" type="xs:string"></xs:element>
			<xs:element name="digest-value" type="DigestValueType"></xs:element>
			<xs:element name="encrypted" type="EncryptedType" minOccurs="0" maxOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="fileref" type="AttachmentFileRefType" use="required"></xs:attribute>
	</xs:complexType>
	<xs:simpleType name="DigestValueType">
		<xs:restriction base="xs:string">
	      <xs:pattern value="[0-9A-Fa-f]+"/>
	    </xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BodyFileRefType">
		<xs:restriction base="xs:string">
	      <xs:pattern value="B[0-9]{7}\.dat"/>
	    </xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AttachmentFileRefType">
		<xs:restriction base="xs:string">
	      <xs:pattern value="A[0-9]{7}\.dat"/>
	    </xs:restriction>
	</xs:simpleType>
	<xs:complexType name="LinkType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="src" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="EncryptedType">
		<xs:sequence>
			<xs:element name="X509Certificate" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== nraa/edelivery-message-format/root/contents/toc.xml
<?xml version="1.0" encoding="UTF-8"?>
<toc
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="toc.xsd">
	<body fileref="B0000001.dat">
		<original-name>cover-letter.html</original-name>
		<!-- digest-values are always _after_ encryption if encryption is used -->
		<digest-algo>SHA-256</digest-algo>
		<digest-value>b402f2558d1a0c6459a141688d42d9b1723aaf0d9d491b774157ea02e78ff983</digest-value>
	</body>
	<attachment-list>
		<attachment fileref="A0000001.dat">
			<original-name>HR-V1_web.pdf</original-name>
			<digest-algo>SHA-256</digest-algo>
			<!-- digest-values are always _after_ encryption if encryption is used -->
			<digest-value>c9cd8bcc4fc98c630dbdb1efa312cbedde677446c37559f4cb032d97bd8910df</digest-value>
		</attachment>
		<attachment fileref="A0000002.dat">
			<original-name>dpr-data.xlsx</original-name>
			<digest-algo>SHA-256</digest-algo>
			<!-- digest-values are always _after_ encryption if encryption is used -->
			<digest-value>75a55a62f6864f1084fbb4c12bbc3c4bb42e7ca7928f7d801e9f35a68847b81a</digest-value>
		</attachment>
	</attachment-list>
	<link-list>
		<link src="http://edrms.nraa.gov.om/permid=30a8j2we89">Online Report 1</link>
		<link src="http://edrms.nraa.gov.om/permid=20d7p2ss54">Online Report 2</link>
	</link-list>
</toc>
